version: "3.8"
networks:
  alsinet:
    external: true
services:
  web:
    build: .
    container_name: bewise_first
    image: bewise_first
    ports:
      - 8080:8000
    volumes:
      - .env:/usr/src/app/bewise_first/.env
    networks:
      - alsinet

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
       - 5432:5432
    networks:
      - alsinet

volumes:
  db-data:
    driver: local