"""Initial db

Revision ID: 4e2ee290df83
Revises: 
Create Date: 2023-05-18 19:35:45.368252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2ee290df83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('q_id', sa.BigInteger(), nullable=False),
    sa.Column('q_text', sa.Text(), nullable=False),
    sa.Column('a_text', sa.Text(), nullable=False),
    sa.Column('q_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('q_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
